{% set name = "lightly" %}
{% set version = "1.15.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Must use GitHub instead of PyPI
  # https://github.com/lightly-ai/lightly/issues/1146
  url: https://github.com/lightly-ai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 947e74aff25965d5f3e647989477e261e2024547db7a71411aa5a3723f419082

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=21
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - certifi >=14.05.14
    - hydra-core >=1.0.0
    - lightly-utils >=0.0.0,<0.1.dev0
    - numpy >=1.18.1
    - python-dateutil >=2.5.3
    - requests >=2.23.0
    - six >=1.10
    - tqdm >=4.44
    - urllib3 >=1.25.3
    - pydantic >=1.10.5
    - aenum >=3.1.11
    - pytorch
    - torchvision
    - pytorch-lightning >=1.0.4

test:
  imports:
    - lightly
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lightly-ai/lightly
  summary: A deep learning package for self-supervised learning
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - IgorSusmelj
    - MalteEbner
    - philippmwirth
    - guarin
